name: 'CD - Deploy Infrastructure'

# Only trigger on push to main or manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Required for deployment
env:
  TF_CLOUD_ORGANIZATION: "rootguru-infotech"
  TF_WORKSPACE: "ec2-deployment"
  TF_LOG: "INFO"

jobs:
  deploy:
    name: 'Deploy to AWS'
    runs-on: ubuntu-latest
    
    # Only run if CI workflow passes
    needs: []  # We'll configure this after testing

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      # Step 1: Check out code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Step 5: Plan Infrastructure Changes
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        continue-on-error: true

      # Step 6: Apply Changes
      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && steps.plan.outcome == 'success'
        run: terraform apply -auto-approve -input=false

      # Step 7: Verify Deployment
      - name: Verify Deployment
        if: steps.apply.outcome == 'success'
        run: |
          echo "Deployment completed successfully"
          terraform output

      # Step 8: Notify on Failure
      - name: Notify on Failure
        if: failure()
        run: |
          echo "Deployment failed"
          echo "Check the logs for more details" 